#!/bin/bash

# You should run this script before commit/push if you made changes to the
# source code of the Finite Magma Explorer in the `src/` directory. It will
# generate the dist directory, which is then used by CI when generating the
# website. This is so that we don't need to have Elm within the CI.

# Prepends a notice not to edit dist/ files
prepend_notice() {
  local file="$1"
  local ext="${file##*.}"
  local notice
  if [ "$ext" == "html" ]; then
    notice="<!-- DO NOT EDIT THIS FILE DIRECTLY. Edit the corresponding file in src/ instead. -->"
    if grep -iq '^<!doctype' "$file"; then
      # notice after the DOCTYPE
      sed -i "0,/^<!doctype[^>]*>/I{/^<!doctype[^>]*>/I a\\
$notice
}" "$file"
    else
      # no DOCTYPE
      echo -e "$notice\n$(cat "$file")" > "$file"
    fi
  elif [ "$ext" == "js" ]; then
    notice="/* DO NOT EDIT THIS FILE DIRECTLY. Edit the corresponding file in src/ instead. */"
    echo -e "$notice\n$(cat "$file")" > "$file"
  elif [ "$ext" == "css" ]; then
    notice="/* DO NOT EDIT THIS FILE DIRECTLY. Edit the corresponding file in src/ instead. */"
    echo -e "$notice\n$(cat "$file")" > "$file"
  fi
}

# Step 1. Build the elm source.
mkdir -p dist
elm make src/Main.elm --optimize --output=dist/elm.js

# Step 2. Deploy the static assets and js.
cp -r src/assets/ dist/
cp src/index.html dist/
cp src/worker.js dist/
cp src/*.json dist/

# Step 3. Find all HTML/js/css files in the dist/ directory and prepend the notice
find dist/ -type f \( -name "*.html" -o -name "*.js" -o -name "*.css" \) | while read -r file; do
    prepend_notice "$file"
done
